spring.application.name=dreamlight-legend

# Hide the giant ASCII Spring banner
spring.main.banner-mode=off

# Stop printing standard startup/profile details
spring.main.log-startup-info=false

# Mute Spring Framework's internal logging noise
logging.level.org.springframework=OFF
